package com.dbmanager.dbmanager.Service;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.json.JSONArray;
import org.json.JSONObject;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.http.HttpEntity;
import org.springframework.http.HttpHeaders;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Service;
import org.springframework.web.client.RestTemplate;

@Service
public class GeminiService {

    @Value("${gemini.api.key}")
    private String geminiApiKey;

    @Value("${gemini.model:gemini-1.5-flash}")
    private String model;

    private final String GEMINI_URL = "https://generativelanguage.googleapis.com/v1beta/models/%s:generateContent?key=%s";

    public String convertToSQL(String userPrompt) {
        String fullPrompt = """
                Convert the following natural language instruction to a MySQL query.
                Assume a table 'users' with columns: id, name, email, created_at.
                Only return the SQL query, nothing else.

                Instruction: %s
                SQL:
                """.formatted(userPrompt);

        RestTemplate restTemplate = new RestTemplate();

        // Build request body according to Gemini API format
        Map<String, Object> requestBody = new HashMap<>();
        
        List<Map<String, Object>> contents = new ArrayList<>();
        Map<String, Object> contentMap = new HashMap<>();
        
        List<Map<String, Object>> partsList = new ArrayList<>();
        Map<String, Object> part = new HashMap<>();
        part.put("text", fullPrompt);
        partsList.add(part);
        
        contentMap.put("parts", partsList);
        contents.add(contentMap);
        
        requestBody.put("contents", contents);
        
        // Generation config
        Map<String, Object> generationConfig = new HashMap<>();
        generationConfig.put("temperature", 0.1);
        generationConfig.put("maxOutputTokens", 150);
        generationConfig.put("topP", 0.8);
        generationConfig.put("topK", 10);
        
        requestBody.put("generationConfig", generationConfig);

        HttpHeaders headers = new HttpHeaders();
        headers.setContentType(MediaType.APPLICATION_JSON);

        HttpEntity<Map<String, Object>> request = new HttpEntity<>(requestBody, headers);

        String url = String.format(GEMINI_URL, model, geminiApiKey);
        
        try {
            ResponseEntity<String> response = restTemplate.postForEntity(url, request, String.class);

            if (response.getStatusCode().is2xxSuccessful()) {
                JSONObject json = new JSONObject(response.getBody());
                
                // Parse Gemini response format
                JSONArray candidates = json.getJSONArray("candidates");
                if (candidates.length() > 0) {
                    JSONObject candidate = candidates.getJSONObject(0);
                    JSONObject responseContent = candidate.getJSONObject("content");
                    JSONArray responseParts = responseContent.getJSONArray("parts");
                    
                    if (responseParts.length() > 0) {
                        String sqlResponse = responseParts.getJSONObject(0).getString("text").trim();
                        
                        // Clean up the response - remove any extra text, keep only SQL
                        String sql = extractSQL(sqlResponse);
                        
                        // Optional: ensure it ends with semicolon
                        return sql.endsWith(";") ? sql : sql + ";";
                    }
                }
                
                throw new RuntimeException("No content generated by Gemini API");
            } else {
                throw new RuntimeException("Gemini API error: " + response.getBody());
            }
        } catch (Exception e) {
            throw new RuntimeException("Error calling Gemini API: " + e.getMessage(), e);
        }
    }
    
    /**
     * Extract SQL query from Gemini response, removing any extra explanatory text
     */
    private String extractSQL(String response) {
        // Look for SQL keywords to identify the actual query
        String[] lines = response.split("\n");
        StringBuilder sqlBuilder = new StringBuilder();
        
        boolean foundSQL = false;
        for (String line : lines) {
            String trimmedLine = line.trim();
            
            // Check if line starts with SQL keywords or is part of SQL
            if (trimmedLine.toLowerCase().matches("^(select|insert|update|delete|create|drop|alter|with).*") 
                || foundSQL && !trimmedLine.isEmpty()) {
                foundSQL = true;
                sqlBuilder.append(trimmedLine).append(" ");
                
                // Stop if we hit explanatory text after SQL
                if (trimmedLine.endsWith(";")) {
                    break;
                }
            }
        }
        
        String sql = sqlBuilder.toString().trim();
        return sql.isEmpty() ? response.trim() : sql;
    }
}