spring.application.name=DB Manager
spring.datasource.url=jdbc:mysql://localhost:3306/project_management
spring.datasource.username=root
spring.datasource.password=admin@123
spring.jpa.hibernate.ddl-auto=update
openai.api.key=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
openai.model=text-davinci-003
gemini.api.key=AIzaSyBaUznsGwtPAYx2HAoRN9Ufr2rO1IWhm00
gemini.model=gemini-1.5-flash
gemini.api.url=https://generativelanguage.googleapis.com/v1beta